= Rapport d’avancement du groupe 2.3
PACT groupe xy (Les plus beaux)
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]
:doctype: book
:stem: latexmath
:source-highlighter: coderay
:toc-title: Table des matières
:toc: macro
:sectnums:
:imagesdir: images


// Partie non numérotée
:sectnums!:
== Les BrocoSix
=== Membres du groupe

* Pierre Rakotondrafara 
* Léa Zerah
* Alaeddine Gabsi
* David Gérard
* Johnathan Loh
* Vincent Josse

=== Tuteur

* Christophe Prieur

=== Encadrant génie logiciel

* Lucien Maman

== Résumé du sujet choisi en français (PAN1)

*_Note: 15 lignes max_*

Le projet que notre groupe va mener pendant cette année est un projet
d'application de nutrition. Elle s'adresse aux étudiants en premier lieu qui
sont souvent livrés sans indice à la cuisine. Plus généralement, elle a pour
but de permettre aux gens d'avoir une alimentation plus saine sans avoir
à écumer des livres de nutrition. Elle s'inscrit donc parmis les initiatives
pour lutter contre l'obésité et est une piste de réponse à la 'malbouffe' qui
est un problème crucial de notre société.
Pour faire cela, l'appli proposeras donc à l'utilisateur d'identifier les
produits qu'il achète de la manière la plus ergonomique possible. Elle pourra
donc lui indiquer la qualité des produits qu'il achète (tant de point de vue
de la santé que d'un point de vue écologique et reponsable). De plus,
seront proposées à l'utilisateur des recettes adaptées à ce qu'il a déjà
renseigné dans l'application, des recettes pour lesquels il ne lui manque que
quelques ingrédients et enfin des propositions des alternatives de produits pour
ses prochaines courses avec des produits qu'il n'a pas qu'il pourrait acheter
pour une alimentation plus saine.

== English Summary (PAN1)

We have chosen to work on an application for nutrition. Intended primarily for 
students who usually do not have any cooking experience, the application aims to
promote healthier eating without conscientiously having to watch our nutritional
intake. This is hence an initiative aimed to combat obesity and the consumption
of junk food - a growing issue in our society. 
To achieve this, the app proposes the most economical and efficient way to 
prepare for our next meals. The products' qualities will also be shown to the 
user (alongside factors such as nutritional values and environmental 
responsibility). Furthermore, the app will propose recipes adapted to what was 
listed in the app, recipes that only lack a few ingredients, as well as 
suggestions on what to purchase the next time for a healthier diet.

*ToDo*

*_Note : 15 lignes max, version anglaise du texte précédent_*


ifndef::backend-pdf[]
== Table des matières
:toc-title:
toc::[]
endif::[]

// On numérote le reste des sections
:sectnums:

== Étude d’antériorité et justification de la proposition (PAN1)

include::proposition/proposition.adoc[Description de la proposition]

include::proposition/etat-de-l-art.adoc[Description de l’état de l’art]

== Scénarios d’usage (PAN1)

include::scenario/scenario.adoc[Scénarios d’usage]

<<<

== Architecture du projet (PAN1)

include::architecture/schema.adoc[Schéma d’architecture]

include::architecture/interfaces.adoc[Description des interfaces]

//include::architecture/sequence.adoc[Diagramme de séquence]

include::architecture/ihm.adoc[Interface utilisateur graphique]

// include::architecture/taches.adoc[Tableau détaillé des tâches] ToDo

<<<

== Organisation du projet (PAN1)

include::organisation/planification.adoc[Diagramme de planification temporel des tâches]

include::organisation/repartition.adoc[Répartition des élèves par module]

//include::organisation/plan-tests.adoc[Plans de test (PAN2+)]

<<<

[bibliography]
== Bibliographie (PAN1+)

include::References.adoc[Bibliographie]

<<<

//== Annexes

//include::annexes/modifications.adoc[Modifications (PAN2+)]

//include::annexes/avancement.adoc[Avancement des modules]

//include::annexes/moduleX.adoc[Avancement module X]

//include::annexes/moduleY.adoc[Avancement module Y]
