=== Description de l’état de l’art
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]

//*_Note : 1 page max._*

//Decrivez, en les citant via la bibliographie, les approches/produits
//ressemblant à votre projet et les différences éventuelles. Illustrez
//avec des images si besoin. Utilisez des renvois vers votre
//bibliographie : « comme démontré dans [2], … »

Les applications proposant le type de service décrit ci-dessus sont multiples.
Néanmoins, elles ont en générales plusieurs défauts. Le premier est le manque
de simplicité d'utilisation. Souvent longues à utiliser, les interfaces
proposées requièrent de l'uitilisateur un grand nombre d'entrées pour 
fonctionner et ceci de manière régulière. Le second défaut principal de ces
applications est de surcharger l'utilisateur d'informations qu'il ne désire pas
forcément, ce qui rend l'application difficile à prendre en main.

Notre objectif est de palier ces défauts.
La manière dont les données sont rentrées doit être simple et efficace. Pour ce
faire, l'utilisateur aura à sa disposition différentes options telles que la
reconnaissance d'image, la lecture de ticket de caisse pour identifier des
aliments. Nous proposons par ailleurs un système de progression qui permettrai 
de faire découvrir des fonctionalités à l'utilisateur de manière progressive 
pour faciliter la prise en main du logiciel.

En ce qui concerne la reconnaissance d'image et de texte pour les entrées, il 
s'agit de cas classiques d'application du machine learning. Pour le côté 
Android, le véritable défi est de réussir à créer une interface interactive  et 
dynamique qui donne envie à l'utilisateur de passer du temps sur l'application. 
Les différentes bibliothèques à disposition permettront de faire une interface 
fonctionnelle relativement vite. Pour le système de progression proposé, nous
disposeront d'une base de donnée où l'on pourra avoir un champ permettant de
quantifier cette progression. Il s'agira ensuite de faire éxecuter des requêtes 
SQL au serveur sur la base de donnée. La récupération de données sur 
<<../References.adoc#OFF,OpenFoodFacts>> ne devrait pas trop poser problème puisque l'on dispose
d'une API.


//==== Exemples de citations

//Les références bibliographiques sont regroupées dans le fichier `References.adoc`
//à la racine du répertoire `rapport`.
//On peut y faire référence dans toutes les sous parties du document.

//On peut citer comme exemple l'article de Claude E. Shannon sur la
//théorie de la communication <<RefShannon>>
//ou, bien évidement, la vitrine des projets PACT <<VitrinePACT>>.

//Voir <<TOTO,la référence>> très intéressante elle aussi.
