=== Description de l’état de l’art
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]

//*_Note : 1 page max._*

//Decrivez, en les citant via la bibliographie, les approches/produits
//ressemblant à votre projet et les différences éventuelles. Illustrez
//avec des images si besoin. Utilisez des renvois vers votre
//bibliographie : « comme démontré dans [2], … »

Il existe de nombreuses applications proposant le même type de service que notre appli Izeat. Cependant, elles ont toutes quelques défauts qui rendent leur utilisation quotidienne un peu compliquée.
Prenons l’exemple de l’application FoodViser, une application de nutrition qui propose les mêmes fonctionnalités qu’Izeat. L’utilisateur doit rentrer un grand nombre d’information pour avoir un suivi précis. En effet, dès la première utilisation, l’application demande de rentrer les petits déjeuners, déjeuners et dîners de manière assez détaillée. Par ailleurs, elle propose des challenges (comme le water challenge) qui surchargent l’interface. L’application est donc très complète voire trop complète…
Par ailleurs, l’application FrigoMagic possède également des fonctionnalisés semblables à Izeat. En effet, c’est un frigo virtuel dans lequel on renseigne les produits que nous possédons, et l’appli nous propose alors des recettes adaptées à ces courses. Cependant, l’interface visuelle n’est pas optimale: les entrées ne sont pas très bien organisées ce qui rend l’utilisation un peu fastidieuse. 

Pour palier tous ces défauts, nous avons décidé de nous concentrer particulièrement sur l’interface visuelle pour la rendre la plus facile possible. En effet, notre objectif est d’avoir une interface épurée qui sera à la fois simple et complète. Les données pourront être rentrées de manière efficace par l’utilisateur pour limiter la perte de temps et lui donner envie d’utiliser l’application quotidiennement. En effet, il aura le choix entre une liste d’aliments, de la reconnaissance d’image (photo d’aliments) et de la lecture d’un tickets de caisse pour identifier ses produits. De plus, l’utilisateur pourra profiter de notre application bien qu’il ne veuille pas rentrer tous les aliments dont il dispose, ce qui rendra l’appli plus facilement utilisable. 

Ainsi, bien que nombreuses applications sur la nutrition existent déjà, nous souhaitons nous démarquer des autres grâce à une interface efficace et épurée qui va rendre l’utilisation de l’appli plus agréable. 


//==== Exemples de citations

//Les références bibliographiques sont regroupées dans le fichier `References.adoc`
//à la racine du répertoire `rapport`.
//On peut y faire référence dans toutes les sous parties du document.

//On peut citer comme exemple l'article de Claude E. Shannon sur la
//théorie de la communication <<RefShannon>>
//ou, bien évidement, la vitrine des projets PACT <<VitrinePACT>>.

//Voir <<TOTO,la référence>> très intéressante elle aussi.
