=== Description des interfaces (PAN1 / PAN2)

//Pour le PAN1, il faut identifier et décrire sommairement toutes les
//interfaces entre modules.
//Pour le PAN2, il faut une description complête des interfaces.
//Il faut ici une description textuelle de chaque interface, c’est à
//dire +
//chaque échange entre deux blocs. Si c’est une interface entre deux
//blocs +
//informatiques, c’est une interface Java. S’il y a des échanges de +
//données complexes, il faut en décrire le format avec grande précision.
//Si c’est une interface +
//entre deux blocs électroniques, c’est une description des signaux +
//électroniques. Etc.

==== Interface OpenFoodFacts - Serveur

Le serveur envoie une requête http à l'API d'OpenFoodFacts et récupère un 
document JSON contenant les informations du produit concerné. On peut aussi 
effectuer une recherche dans OpenFoodFacts, le résultat retourné sera alors
un document HTML.

[source,java]
----
public interface ToolsInterface {

    /* What it does: Gives methods to retrieve queries result from OpenFoodFacts as
     * a  String. This String contains the JSON file's content.
     * What it does not: Format data so that it is ready to be used. See Product class for that purpose.
     * 
     * code is a 12-13 digits integer corresponding to the barcode of the desired
     * product. It is represented as a string as every 0 at the begining matters.
     * Returns a String containing the JSON file.
     * If the method fails to get the JSON file, it will return null.
     */
    public static String getProductQuery(String code) {
        return null;
    }

    /* query corresponds to the search field.
     * pageNumber corresponds to the desired page number of the research result.
     * pageSize corresponds to the number of products by page.
     * Returns a String containing the JSON file with every products that matched the research terms.
     * If the method fails to get the JSON doc, it will return null.
     */
    public static String getSearchQuery(String query, int pageNumber, int pageSize) {
        return null;
    }
----

==== Interface Android - Serveur

Le serveur disposera de son propre service web permettant au client Android
de récupérer les informations essentielles concernant des produits ou des 
données personelles de l'uitilsateur.

Le serveur donne les infos sur les utilisateurs et le produits sous forme de 
fichier json à travers les URI du service web. Le client effectue une requête 
http GET vers le web service afin de récupérer ces .json.



