=== Description des interfaces (PAN1 / PAN2)

Pour le PAN1, il faut identifier et décrire sommairement toutes les
interfaces entre modules.

//Pour le PAN2, il faut une description complête des interfaces.

//Il faut ici une description textuelle de chaque interface, c’est à
//dire +
//chaque échange entre deux blocs. Si c’est une interface entre deux
//blocs +
//informatiques, c’est une interface Java. S’il y a des échanges de +
//données complexes, il faut en décrire le format avec grande précision.
//Si c’est une interface +
//entre deux blocs électroniques, c’est une description des signaux +
//électroniques. Etc.

==== Interface OpenFoodFacts - Serveur

Le serveur envoie une requête http à l'API d'OpenFoodFacts et récupère un 
document JSON contenant les informations du produit concerné. On peut aussi 
effectuer une recherche dans OpenFoodFacts, le résultat retourné sera alors
un document HTML.

[source,java]
----
public interface ToolsInterface {
	// Class inspired by the official Python release of the OpenFoodFacts' SDK.
	// What it does: Gives methods to retrieve queries result from OpenFoodFacts as
	// a StringBuilder object. This StringBuilder contains the JSON file's content.
	// What it does not: Format data so that it is ready to be used.

	// code is a 12 digits integer corresponding to the barcode of the desired
	// product.
	// Returns a StringBuilder containing the JSON file.
	public static StringBuilder getProductQuery(int code) {
		return null;
	}

	// query corresponds to the search field.
	// pageNumber corresponds to the desired page number of the research result.
	// pageSize corresponds to the number of products by page.
	// Returns a StringBuilder containing the HTML doc.
	public static StringBuilder getSearchQuery(String query, int pageNumber, int pageSize) {
		return null;
	}

}

----

==== InterfaceBloc2-4

Description textuelle d’interface
